from __future__ import annotations

import pytest
from pydantic import ValidationError

from ai_server.models import (
    AttackGraph,
    AttackObjective,
    AttackStep,
    MachineInformation,
    ScenarioDraft,
)


def step(step_id: str, *, requires=None, achieves=None) -> AttackStep:
    return AttackStep(
        step_id=step_id,
        title=step_id,
        kind="web_vulnerability",
        phase="initial_access",
        description="training step",
        requires=requires or [],
        achieves=achieves or [],
        implementation_steps=["provision the training condition"],
    )


def test_attack_graph_supports_chained_steps_and_multiple_objectives() -> None:
    graph = AttackGraph(
        objectives=[
            AttackObjective(
                objective_id="user-flag",
                objective_type="user_flag",
                description="user objective",
            ),
            AttackObjective(
                objective_id="system-flag",
                objective_type="system_flag",
                description="system objective",
            ),
        ],
        steps=[
            step("web-entry"),
            step("user-access", requires=["web-entry"], achieves=["user-flag"]),
            step("local-chain", requires=["user-access"]),
            step("root-access", requires=["local-chain"], achieves=["system-flag"]),
        ],
    )

    assert len(graph.steps) == 4


def test_attack_graph_rejects_cycles() -> None:
    with pytest.raises(ValidationError, match="contains a cycle"):
        AttackGraph(
            steps=[
                step("first", requires=["second"]),
                step("second", requires=["first"]),
            ]
        )


def test_attack_graph_rejects_unachieved_flag() -> None:
    with pytest.raises(ValidationError, match="not achieved"):
        AttackGraph(
            objectives=[
                AttackObjective(
                    objective_id="user-flag",
                    objective_type="user_flag",
                    description="user objective",
                )
            ],
            steps=[step("web-entry")],
        )


def test_non_cve_step_rejects_cve_id() -> None:
    with pytest.raises(ValidationError, match="only valid when kind is cve"):
        AttackStep(
            step_id="web-entry",
            title="web entry",
            kind="web_vulnerability",
            phase="initial_access",
            description="training step",
            cve_id="CVE-2026-1234",
            implementation_steps=["provision"],
        )


def test_scenario_rejects_noncanonical_flag_case() -> None:
    with pytest.raises(ValidationError, match="user_flag"):
        ScenarioDraft(
            scenario_id="scenario-invalid-flag",
            title="Invalid flag",
            definition="# Invalid flag",
            attack_graph=AttackGraph(steps=[step("entry")]),
            user_flag="FLAG{USER_A1D51D7F803F51F0356F3E547C842A0B}",
        )


def test_flag_details_reject_server_managed_flag_value() -> None:
    with pytest.raises(ValidationError, match="flag values are generated by the server"):
        MachineInformation(
            name="Invalid details",
            visibility="private",
            theme="Web",
            difficulty="Easy",
            needs_user_flag=True,
            user_flag_details="flag{user_a1d51d7f803f51f0356f3e547c842a0b}",
        )


def test_flag_details_promote_cves_to_dedicated_field() -> None:
    promoted = MachineInformation(
        name="Promoted CVE details",
        visibility="private",
        theme="Web",
        difficulty="Easy",
        needs_user_flag=True,
        user_flag_details="CVE-2026-42533を用いたRCE。",
    )
    assert promoted.cve_ids == ["CVE-2026-42533"]

    deduplicated = MachineInformation(
        name="Explicit CVE details",
        visibility="private",
        theme="Web",
        difficulty="Easy",
        needs_user_flag=True,
        user_flag_details="Exploit cve-2026-42533 to obtain the user flag",
        cve_ids=["CVE-2026-42533"],
    )
    assert deduplicated.cve_ids == ["CVE-2026-42533"]
