from __future__ import annotations

import re
from datetime import UTC, datetime
from enum import StrEnum
from typing import Annotated, Literal

from pydantic import BaseModel, Field, field_validator, model_validator

USER_FLAG_VALUE_PATTERN = re.compile(r"^flag\{user_[0-9a-f]{32}\}$")
SYSTEM_FLAG_VALUE_PATTERN = re.compile(r"^flag\{system_[0-9a-f]{32}\}$")
SCENARIO_DEFINITION_MAX_CHARS = 12_000
ROCKYOU_PASSWORD_PLACEHOLDER = "__SLSG_ROCKYOU_PASSWORD__"


def rockyou_password_placeholder(step_id: str) -> str:
    if not re.fullmatch(r"[a-z][a-z0-9_-]{0,63}", step_id):
        raise ValueError(f"invalid attack step ID for rockyou placeholder: {step_id}")
    return f"__SLSG_ROCKYOU_PASSWORD_{step_id}__"


def utcnow() -> datetime:
    return datetime.now(UTC)


class SessionStatus(StrEnum):
    CREATED = "created"
    READY = "ready"
    GENERATING_SCENARIO = "generating_scenario"
    SCENARIO_READY = "scenario_ready"
    GENERATING_CODE = "generating_code"
    BUILD_QUEUED = "build_queued"
    BUILDING = "building"
    COMPLETED = "completed"
    FAILED = "failed"
    CANCELLED = "cancelled"


class MachineInformation(BaseModel):
    name: str = Field(min_length=1, max_length=40)
    visibility: Literal["private", "public", "非公開", "公開"]
    theme: str = Field(min_length=1, max_length=500)
    difficulty: Literal["Very Easy", "Easy", "Medium", "High"]
    operating_system: str = Field(default="Debian 13.7.0", min_length=1, max_length=100)
    needs_user_flag: bool | None = None
    user_flag_details: str = Field(default="", max_length=4000)
    needs_system_flag: bool | None = None
    system_flag_details: str = Field(default="", max_length=4000)
    skill_names: (
        list[Annotated[str, Field(pattern=r"^[a-z0-9]+(?:-[a-z0-9]+)*$", max_length=64)]] | None
    ) = Field(default=None, max_length=32)
    cve_ids: list[Annotated[str, Field(pattern=r"^CVE-\d{4}-\d{4,7}$")]] = Field(
        default_factory=list, max_length=20
    )

    @model_validator(mode="before")
    @classmethod
    def promote_flag_detail_cves(cls, value):
        if not isinstance(value, dict):
            return value
        normalized = dict(value)
        explicit = list(normalized.get("cve_ids") or [])
        seen = set(explicit)
        for field_name in ("user_flag_details", "system_flag_details"):
            details = str(normalized.get(field_name) or "")
            for cve_id in re.findall(r"CVE-\d{4}-\d{4,7}", details, re.IGNORECASE):
                canonical = cve_id.upper()
                if canonical not in seen:
                    explicit.append(canonical)
                    seen.add(canonical)
        normalized["cve_ids"] = explicit
        return normalized

    @field_validator("skill_names", "cve_ids")
    @classmethod
    def unique_skill_choices(cls, values):
        if values is not None and len(values) != len(set(values)):
            raise ValueError("Skill names and CVE IDs must not contain duplicates")
        return values

    @field_validator("operating_system", mode="before")
    @classmethod
    def default_operating_system(cls, value):
        if value is None or not str(value).strip():
            return "Debian 13.7.0"
        value = str(value).strip()
        match = re.fullmatch(r"debian\s+(\d+(?:\.\d+){0,2})", value, re.IGNORECASE)
        if not match:
            raise ValueError("Only versioned Debian base images are supported (e.g. Debian 13.7.0)")
        return f"Debian {match.group(1)}"

    @model_validator(mode="after")
    def validate_flag_details(self) -> MachineInformation:
        if self.needs_user_flag is True and not self.user_flag_details.strip():
            raise ValueError("user_flag_details is required when needs_user_flag is true")
        if self.needs_system_flag is True and not self.system_flag_details.strip():
            raise ValueError("system_flag_details is required when needs_system_flag is true")
        for field_name, details in (
            ("user_flag_details", self.user_flag_details),
            ("system_flag_details", self.system_flag_details),
        ):
            stripped = details.strip()
            if re.fullmatch(r"flag\{[^{}]+\}", stripped, re.IGNORECASE):
                raise ValueError(
                    f"{field_name} describes acquisition requirements; flag values are "
                    "generated by the server"
                )
        return self


class AttackObjective(BaseModel):
    objective_id: str = Field(pattern=r"^[a-z][a-z0-9_-]{0,63}$")
    objective_type: Literal["user_flag", "system_flag"]
    description: str = Field(min_length=1, max_length=4000)


class PasswordCrackingSpec(BaseModel):
    wordlist: Literal["rockyou.txt"]
    password: str | None = Field(
        default=None, min_length=8, max_length=32, pattern=r"^[A-Za-z0-9]+$"
    )
    line_number: int | None = Field(default=None, ge=1)
    search_space_lines: int | None = Field(default=None, ge=1)
    hash_algorithm: str = Field(min_length=1, max_length=100)
    hash_runtime: str = Field(min_length=1, max_length=100)
    hash_api: str = Field(min_length=1, max_length=200)
    hashcat_mode: int | None = Field(default=None, ge=0)
    john_format: str | None = Field(default=None, min_length=1, max_length=100)
    target_crack_seconds: int = Field(ge=120, le=180)

    @model_validator(mode="after")
    def validate_cracking_parameters(self) -> PasswordCrackingSpec:
        selection = (self.password, self.line_number, self.search_space_lines)
        if any(value is None for value in selection) and any(
            value is not None for value in selection
        ):
            raise ValueError(
                "rockyou selection fields must be all unset or all populated"
            )
        if (
            self.line_number is not None
            and self.search_space_lines is not None
            and self.line_number > self.search_space_lines
        ):
            raise ValueError("password line must be within the declared search space")
        if self.hashcat_mode is None and self.john_format is None:
            raise ValueError("password cracking requires a Hashcat mode or John format")
        return self

    @property
    def selection_bound(self) -> bool:
        return self.password is not None


class AttackStep(BaseModel):
    step_id: str = Field(pattern=r"^[a-z][a-z0-9_-]{0,63}$")
    title: str = Field(min_length=1, max_length=200)
    kind: str = Field(min_length=1, max_length=64)
    phase: str = Field(min_length=1, max_length=64)
    description: str = Field(min_length=1, max_length=4000)
    requires: list[str] = Field(default_factory=list, max_length=20)
    achieves: list[str] = Field(default_factory=list, max_length=10)
    cve_id: str | None = Field(default=None, pattern=r"^CVE-\d{4}-\d{4,7}$")
    cve_title: str | None = Field(default=None, max_length=500)
    cve_description: str | None = Field(default=None, max_length=4000)
    cwe_ids: list[str] = Field(default_factory=list, max_length=30)
    installation_artifact: (
        Literal[
            "os_repository_package",
            "vendor_repository_package",
            "vendor_release_binary",
            "other_prebuilt",
            "source_build",
        ]
        | None
    ) = None
    artifact_source: str | None = Field(default=None, max_length=1000)
    source_build_reason: str | None = Field(default=None, max_length=2000)
    software: str | None = Field(default=None, max_length=200)
    vulnerable_version: str | None = Field(default=None, max_length=200)
    os_compatible: bool | None = None
    compatibility_reason: str | None = Field(default=None, max_length=2000)
    installation_method: str | None = Field(default=None, max_length=500)
    implementation_steps: list[str] = Field(min_length=1, max_length=50)
    references: list[str] = Field(default_factory=list, max_length=30)
    password_cracking: PasswordCrackingSpec | None = None

    @model_validator(mode="after")
    def validate_cve_fields(self) -> AttackStep:
        if self.kind == "cve" and not self.cve_id:
            raise ValueError("a cve attack step requires cve_id")
        if self.kind != "cve" and self.cve_id:
            raise ValueError("cve_id is only valid when kind is cve")
        if self.kind != "cve" and (self.cve_title or self.cve_description or self.cwe_ids):
            raise ValueError("official CVE facts are only valid when kind is cve")
        if self.kind != "cve" and (
            self.installation_artifact or self.artifact_source or self.source_build_reason
        ):
            raise ValueError("CVE installation evidence is only valid when kind is cve")
        if self.installation_artifact == "source_build" and not self.source_build_reason:
            raise ValueError("source-built CVE software requires a source_build_reason")
        if self.kind == "password_cracking" and self.password_cracking is None:
            raise ValueError("a password_cracking step requires password_cracking metadata")
        if self.kind != "password_cracking" and self.password_cracking is not None:
            raise ValueError(
                "password_cracking metadata is only valid when kind is password_cracking"
            )
        return self


class AttackGraph(BaseModel):
    objectives: list[AttackObjective] = Field(default_factory=list, max_length=10)
    steps: list[AttackStep] = Field(min_length=1, max_length=30)

    @model_validator(mode="after")
    def validate_graph(self) -> AttackGraph:
        objective_ids = [objective.objective_id for objective in self.objectives]
        if len(objective_ids) != len(set(objective_ids)):
            raise ValueError("attack objective IDs must be unique")
        objective_types = [objective.objective_type for objective in self.objectives]
        if len(objective_types) != len(set(objective_types)):
            raise ValueError("attack objective types must be unique")

        step_ids = [step.step_id for step in self.steps]
        if len(step_ids) != len(set(step_ids)):
            raise ValueError("attack step IDs must be unique")
        known_steps = set(step_ids)
        known_objectives = set(objective_ids)
        for step in self.steps:
            if len(step.requires) != len(set(step.requires)):
                raise ValueError(f"attack step {step.step_id} has duplicate requirements")
            if len(step.achieves) != len(set(step.achieves)):
                raise ValueError(f"attack step {step.step_id} has duplicate objectives")
            if step.step_id in step.requires:
                raise ValueError(f"attack step {step.step_id} cannot require itself")
            unknown_steps = set(step.requires) - known_steps
            if unknown_steps:
                raise ValueError(
                    f"attack step {step.step_id} has unknown requirements: {sorted(unknown_steps)}"
                )
            unknown_objectives = set(step.achieves) - known_objectives
            if unknown_objectives:
                raise ValueError(
                    f"attack step {step.step_id} has unknown objectives: "
                    f"{sorted(unknown_objectives)}"
                )

        self._validate_acyclic_graph()
        achieved = {objective for step in self.steps for objective in step.achieves}
        missing = known_objectives - achieved
        if missing:
            raise ValueError(f"attack objectives are not achieved by any step: {sorted(missing)}")
        return self

    def _validate_acyclic_graph(self) -> None:
        dependencies = {step.step_id: step.requires for step in self.steps}
        visiting: set[str] = set()
        visited: set[str] = set()

        def visit(step_id: str) -> None:
            if step_id in visiting:
                raise ValueError(f"attack graph contains a cycle at {step_id}")
            if step_id in visited:
                return
            visiting.add(step_id)
            for dependency in dependencies[step_id]:
                visit(dependency)
            visiting.remove(step_id)
            visited.add(step_id)

        for step_id in dependencies:
            visit(step_id)


class ScenarioDraft(BaseModel):
    scenario_id: str
    scenario_version_id: str = "v1"
    title: str
    scenario_description: str = Field(default="", max_length=1000)
    definition: str = Field(min_length=1, max_length=SCENARIO_DEFINITION_MAX_CHARS)
    target_os: str = "Debian 13.7.0"
    attack_graph: AttackGraph
    user_flag: str | None = Field(
        default=None,
        min_length=22,
        max_length=134,
        pattern=r"^flag\{[A-Za-z0-9][A-Za-z0-9_-]{15,127}\}$",
        exclude=True,
    )
    system_flag: str | None = Field(
        default=None,
        min_length=22,
        max_length=134,
        pattern=r"^flag\{[A-Za-z0-9][A-Za-z0-9_-]{15,127}\}$",
        exclude=True,
    )

    @model_validator(mode="after")
    def flags_must_be_distinct(self) -> ScenarioDraft:
        if self.user_flag and self.system_flag and self.user_flag == self.system_flag:
            raise ValueError("user_flag and system_flag must be different")
        return self


def scenario_is_valid_for_machine(machine: MachineInformation, scenario: ScenarioDraft) -> bool:
    """Return whether a persisted scenario still matches normalized machine requirements."""

    expected = (
        (machine.needs_user_flag is True, scenario.user_flag, USER_FLAG_VALUE_PATTERN),
        (machine.needs_system_flag is True, scenario.system_flag, SYSTEM_FLAG_VALUE_PATTERN),
    )
    flags_are_valid = all(
        bool(pattern.fullmatch(value or "")) if required else value is None
        for required, value, pattern in expected
    )
    scenario_cves = {
        step.cve_id: step for step in scenario.attack_graph.steps if step.cve_id is not None
    }
    requested_cves_are_grounded = all(
        cve_id in scenario_cves
        and bool(scenario_cves[cve_id].cve_title)
        and bool(scenario_cves[cve_id].cve_description)
        for cve_id in machine.cve_ids
    )
    return flags_are_valid and requested_cves_are_grounded


class ScenarioReviewFinding(BaseModel):
    step_id: str | None = Field(default=None, max_length=128)
    severity: Literal["error", "warning"]
    category: Literal[
        "permission_blocker",
        "permission_shortcut",
        "broken_chain",
        "semantic_mismatch",
        "implementation_gap",
        "unintended_shortcut",
        "acceptance_test_gap",
        "unsupported_assumption",
        "description_spoiler",
        "input_contradiction",
    ]
    repair_target: Literal[
        "scenario_text",
        "attack_graph",
        "attack_graph_regeneration",
        "source_code",
        "user_input",
    ] = "scenario_text"
    repair_fields: list[str] = Field(default_factory=list, max_length=30)
    evidence: str = Field(min_length=1, max_length=4000)
    remediation: str = Field(min_length=1, max_length=4000)

    @model_validator(mode="after")
    def repair_fields_match_target(self) -> ScenarioReviewFinding:
        allowed_graph_fields = {"title", "description", "implementation_steps"}
        allowed_regeneration_fields = {
            "step_id",
            "kind",
            "phase",
            "requires",
            "achieves",
            "cve_id",
            "password_cracking",
        }
        allowed_input_fields = {
            "theme",
            "user_flag_details",
            "system_flag_details",
            "skill_names",
            "cve_ids",
        }
        fields = set(self.repair_fields)
        if self.repair_target == "attack_graph":
            if not fields or not fields <= allowed_graph_fields:
                raise ValueError(
                    "attack_graph repair_fields must only contain title, description, "
                    "or implementation_steps"
                )
        elif self.repair_target == "attack_graph_regeneration":
            if not fields or not fields <= allowed_regeneration_fields:
                raise ValueError(
                    "attack_graph_regeneration repair_fields must contain structural fields"
                )
        elif self.repair_target == "user_input":
            if not fields or not fields <= allowed_input_fields:
                raise ValueError(
                    "user_input repair_fields must identify contradictory machine input fields"
                )
        elif fields:
            raise ValueError(
                f"repair_fields must be empty for repair_target={self.repair_target}"
            )
        if self.repair_target == "user_input" and (
            self.category != "input_contradiction" or self.step_id is not None
        ):
            raise ValueError(
                "user_input is only valid for an explicit input_contradiction without "
                "a generated attack-graph step_id"
            )
        if self.category == "input_contradiction" and self.repair_target != "user_input":
            raise ValueError("input_contradiction findings must target user_input")
        return self


class ScenarioReview(BaseModel):
    approved: bool
    summary: str = Field(min_length=1, max_length=4000)
    findings: list[ScenarioReviewFinding] = Field(default_factory=list, max_length=100)

    @model_validator(mode="after")
    def approval_matches_findings(self) -> ScenarioReview:
        has_error = any(finding.severity == "error" for finding in self.findings)
        if self.approved == has_error:
            raise ValueError("approved must be true exactly when there are no error findings")
        return self


class ScenarioRevision(BaseModel):
    scenario_description: str = Field(min_length=1, max_length=1000)
    definition: str = Field(min_length=1, max_length=SCENARIO_DEFINITION_MAX_CHARS)
    attack_graph: AttackGraph
    summary: str = Field(min_length=1, max_length=4000)


class ScenarioTextRevision(BaseModel):
    scenario_description: str = Field(min_length=1, max_length=1000)
    definition: str = Field(min_length=1, max_length=SCENARIO_DEFINITION_MAX_CHARS)
    summary: str = Field(min_length=1, max_length=4000)


class ScenarioGeneration(BaseModel):
    scenario_description: str = Field(min_length=1, max_length=1000)
    definition: str = Field(min_length=1, max_length=SCENARIO_DEFINITION_MAX_CHARS)


class ScenarioTextReplacement(BaseModel):
    old: str = Field(min_length=1, max_length=4000)
    new: str = Field(max_length=5000)


class ScenarioCorrection(BaseModel):
    scenario_description: str | None = Field(default=None, min_length=1, max_length=1000)
    definition_replacements: list[ScenarioTextReplacement] = Field(max_length=20)

    @model_validator(mode="after")
    def require_a_change(self) -> ScenarioCorrection:
        if self.scenario_description is None and not self.definition_replacements:
            raise ValueError("scenario correction must contain at least one change")
        return self


class SourceReviewFinding(BaseModel):
    step_id: str | None = Field(default=None, max_length=128)
    severity: Literal["error", "warning"]
    repair_target: Literal[
        "source_code",
        "scenario_text",
    ] = "source_code"
    category: Literal[
        "wrong_technique",
        "unintended_shortcut",
        "unproven_exploit",
        "broken_chain",
        "acceptance_test_gap",
        "implementation_mismatch",
    ]
    affected_files: list[str] = Field(default_factory=list, max_length=30)
    evidence: str = Field(min_length=1, max_length=4000)
    remediation: str = Field(min_length=1, max_length=4000)


class SourceReview(BaseModel):
    approved: bool
    summary: str = Field(min_length=1, max_length=4000)
    findings: list[SourceReviewFinding] = Field(default_factory=list, max_length=100)

    @model_validator(mode="after")
    def approval_matches_findings(self) -> SourceReview:
        has_error = any(finding.severity == "error" for finding in self.findings)
        if self.approved == has_error:
            raise ValueError("approved must be true exactly when there are no error findings")
        return self


class SourceFile(BaseModel):
    path: str
    content: str
    mode: Literal["0600", "0640", "0644", "0700", "0750", "0755"] = "0644"


class GeneratedSource(BaseModel):
    files: list[SourceFile] = Field(min_length=1, max_length=100)


class GuidanceItem(BaseModel):
    target_flag: Literal["user", "system"]
    title: str = Field(min_length=1, max_length=120)
    question: str = Field(min_length=1, max_length=500)
    hint: str = Field(min_length=1, max_length=1000)


class GuidancePlan(BaseModel):
    introduction: str = Field(min_length=1, max_length=1000)
    items: list[GuidanceItem] = Field(max_length=8)


class GuidanceRequest(BaseModel):
    acquired_flags: list[Literal["user", "system"]] = Field(default_factory=list, max_length=2)

    @field_validator("acquired_flags")
    @classmethod
    def acquired_flags_are_unique(cls, values):
        if len(values) != len(set(values)):
            raise ValueError("acquired flags must not contain duplicates")
        return values


class SourcePatch(BaseModel):
    files: list[SourceFile] = Field(default_factory=list, max_length=50)
    delete_paths: list[str] = Field(default_factory=list, max_length=50)

    @model_validator(mode="after")
    def require_a_change(self) -> SourcePatch:
        if not self.files and not self.delete_paths:
            raise ValueError("source patch must change or delete at least one file")
        return self


class SourceWorkbenchCommand(BaseModel):
    argv: list[str] = Field(min_length=1, max_length=32)
    cwd: str = Field(default="contents", min_length=1, max_length=500)
    purpose: str = Field(min_length=1, max_length=1000)
    network_access: bool = False
    run_as_root: bool = False

    @field_validator("argv")
    @classmethod
    def command_arguments_are_bounded(cls, values: list[str]) -> list[str]:
        if any(not value or len(value) > 1000 or "\x00" in value for value in values):
            raise ValueError("workbench command arguments must be non-empty bounded strings")
        return values


class SourceWorkbenchDecision(BaseModel):
    action: Literal["run", "finish"]
    command: SourceWorkbenchCommand | None = None
    summary: str = Field(min_length=1, max_length=2000)

    @model_validator(mode="after")
    def command_matches_action(self) -> SourceWorkbenchDecision:
        if (self.action == "run") != (self.command is not None):
            raise ValueError("command is required exactly when action is run")
        return self


class Artifact(BaseModel):
    artifact_id: str
    artifact_type: str
    file_name: str
    file_size: int
    checksum: str


class MachineAccess(BaseModel):
    username: str = Field(min_length=1, max_length=100)
    password: str = Field(min_length=1, max_length=500)


class SessionState(BaseModel):
    session_id: str
    owner_user_id: str
    status: SessionStatus = SessionStatus.CREATED
    machine_information: MachineInformation | None = None
    scenario: ScenarioDraft | None = None
    source_path: str | None = None
    source_checksum: str | None = None
    scenario_generation_attempts: int = Field(default=0, ge=0, exclude=True)
    scenario_generation_attempt_limit: int = Field(default=0, ge=0, exclude=True)
    source_generation_attempts: int = Field(default=0, ge=0, exclude=True)
    source_generation_attempt_limit: int = Field(default=0, ge=0, exclude=True)
    scenario_sync_attempts: int = Field(default=0, ge=0, exclude=True)
    scenario_sync_attempt_limit: int = Field(default=0, ge=0, exclude=True)
    build_id: str | None = None
    build_status: str | None = None
    build_progress: int = 0
    build_repair_attempts: int = Field(
        default=0,
        ge=0,
        description="Cumulative number of submitted build repair attempts",
    )
    build_repair_attempt_limit: int = Field(default=0, ge=0, exclude=True)
    repair_failure_report: dict | None = Field(default=None, exclude=True)
    machine_access: MachineAccess | None = None
    artifact: Artifact | None = None
    error_message: str | None = None
    created_at: datetime = Field(default_factory=utcnow)
    updated_at: datetime = Field(default_factory=utcnow)


class CreateMachineRequest(BaseModel):
    scenario_id: str | None = None


class SessionResponse(SessionState):
    scenario_events_url: str
    download_url: str | None = None
    user_flag: str | None = None
    system_flag: str | None = None


class DownloadURLResponse(BaseModel):
    download_url: str
    expires_at: datetime
