export const SEED_USERS = [
  {
    id: "seed-user-alice",
    name: "アリス",
    bio: "Webセキュリティを学習中です。",
    theme: "dark",
    createdAt: "2026-08-01T00:00:00.000Z",
  },
  {
    id: "seed-user-bob",
    name: "ボブ",
    bio: "コンテナとネットワークが好きです。",
    theme: "light",
    createdAt: "2026-08-02T00:00:00.000Z",
  },
  {
    id: "seed-user-carol",
    name: "キャロル",
    bio: "ログ分析とインシデント対応を勉強しています。",
    theme: "light",
    createdAt: "2026-08-03T00:00:00.000Z",
  },
] as const

export const SEED_MACHINES = [
  {
    id: "seed-machine-web-auth",
    createdBy: "seed-user-alice",
    name: "Web認証ラボ",
    description:
      "Webアプリケーションのログイン処理に潜む問題を調査し、適切な認証設計を学ぶ公開マシンです。",
    level: "easy",
    systemFlag: "flag{seed-web-auth-system}",
    userFlag: "flag{seed-web-auth-user}",
    tags: ["Web セキュリティ", "認証・認可"],
    createdAt: "2026-08-04T00:00:00.000Z",
  },
  {
    id: "seed-machine-container-network",
    createdBy: "seed-user-bob",
    name: "コンテナネットワーク調査",
    description:
      "コンテナのネットワーク設定を確認し、意図しない通信経路や公開ポートを見つける公開マシンです。",
    level: "medium",
    systemFlag: "flag{seed-container-system}",
    userFlag: "",
    tags: ["コンテナ", "ネットワーク"],
    createdAt: "2026-08-08T00:00:00.000Z",
  },
  {
    id: "seed-machine-linux-permissions",
    createdBy: "seed-user-alice",
    name: "Linux権限管理",
    description:
      "Linuxのファイル所有者、グループ、実行権限を確認し、過剰な権限を特定する公開マシンです。",
    level: "easy",
    systemFlag: "flag{seed-linux-permissions}",
    userFlag: "",
    tags: ["Linux", "権限管理"],
    createdAt: "2026-08-12T00:00:00.000Z",
  },
  {
    id: "seed-machine-log-trail",
    createdBy: "seed-user-carol",
    name: "ログ追跡演習",
    description:
      "認証ログとアクセスログを時系列で照合し、インシデントの起点と影響範囲を調査する公開マシンです。",
    level: "medium",
    systemFlag: "",
    userFlag: "flag{seed-log-trail}",
    tags: ["ログ分析", "インシデント対応"],
    createdAt: "2026-08-16T00:00:00.000Z",
  },
  {
    id: "seed-machine-api-authorization",
    createdBy: "seed-user-bob",
    name: "API認可チャレンジ",
    description:
      "利用者ごとのアクセス制御を確認し、認可検証の不足による情報露出を調査する公開マシンです。",
    level: "hard",
    systemFlag: "flag{seed-api-authorization-system}",
    userFlag: "flag{seed-api-authorization-user}",
    tags: ["API", "認証・認可"],
    createdAt: "2026-08-20T00:00:00.000Z",
  },
  {
    id: "seed-machine-sql-investigation",
    createdBy: "seed-user-carol",
    name: "SQL調査ラボ",
    description:
      "アプリケーションの入力処理とデータベース権限を確認し、安全なSQL操作を学ぶ公開マシンです。",
    level: "hard",
    systemFlag: "flag{seed-sql-investigation}",
    userFlag: "",
    tags: ["データベース", "入力値検証"],
    createdAt: "2026-08-24T00:00:00.000Z",
  },
  {
    id: "seed-machine-http-headers",
    createdBy: "seed-user-alice",
    name: "HTTPヘッダー調査",
    description:
      "HTTPレスポンスヘッダーを比較し、情報露出とブラウザ側の保護設定を学ぶ公開マシンです。",
    level: "easy",
    systemFlag: "flag{seed-http-headers}",
    userFlag: "",
    tags: ["Web セキュリティ", "HTTP"],
    createdAt: "2026-08-25T00:00:00.000Z",
  },
  {
    id: "seed-machine-ssh-access",
    createdBy: "seed-user-bob",
    name: "SSHアクセス制御",
    description: "SSHの認証設定とアクセス制御を調べ、安全なリモート接続を考える公開マシンです。",
    level: "easy",
    systemFlag: "flag{seed-ssh-access}",
    userFlag: "",
    tags: ["Linux", "認証・認可"],
    createdAt: "2026-08-26T00:00:00.000Z",
  },
  {
    id: "seed-machine-dns-records",
    createdBy: "seed-user-carol",
    name: "DNSレコード調査",
    description: "DNSレコードと名前解決の結果を調べ、公開情報の管理を学ぶ公開マシンです。",
    level: "medium",
    systemFlag: "flag{seed-dns-records}",
    userFlag: "",
    tags: ["ネットワーク", "DNS"],
    createdAt: "2026-08-27T00:00:00.000Z",
  },
  {
    id: "seed-machine-session-cookie",
    createdBy: "seed-user-alice",
    name: "セッションCookie演習",
    description: "ログイン後のCookieを確認し、セッションの保護に必要な設定を学ぶ公開マシンです。",
    level: "very_easy",
    systemFlag: "flag{seed-session-cookie-system}",
    userFlag: "flag{seed-session-cookie-user}",
    tags: ["Web セキュリティ", "セッション管理"],
    createdAt: "2026-08-28T00:00:00.000Z",
  },
  {
    id: "seed-machine-firewall-rules",
    createdBy: "seed-user-bob",
    name: "ファイアウォール設定",
    description:
      "ファイアウォールのルールを検証し、必要な通信だけを許可する方法を学ぶ公開マシンです。",
    level: "medium",
    systemFlag: "flag{seed-firewall-rules}",
    userFlag: "",
    tags: ["ネットワーク", "アクセス制御"],
    createdAt: "2026-08-29T00:00:00.000Z",
  },
  {
    id: "seed-machine-audit-log",
    createdBy: "seed-user-carol",
    name: "監査ログ分析",
    description: "監査ログを時系列で照合し、権限変更の経路を追う公開マシンです。",
    level: "medium",
    systemFlag: "",
    userFlag: "flag{seed-audit-log}",
    tags: ["ログ分析", "権限管理"],
    createdAt: "2026-08-30T00:00:00.000Z",
  },
  {
    id: "seed-machine-api-rate-limit",
    createdBy: "seed-user-alice",
    name: "APIレート制限",
    description: "APIの利用制限を確認し、過剰なアクセスへの対処を学ぶ公開マシンです。",
    level: "hard",
    systemFlag: "flag{seed-api-rate-limit}",
    userFlag: "",
    tags: ["API", "アクセス制御"],
    createdAt: "2026-08-31T00:00:00.000Z",
  },
  {
    id: "seed-machine-container-secrets",
    createdBy: "seed-user-bob",
    name: "コンテナ秘密情報管理",
    description: "コンテナ内の設定を調べ、秘密情報の扱いと公開範囲を学ぶ公開マシンです。",
    level: "hard",
    systemFlag: "flag{seed-container-secrets}",
    userFlag: "",
    tags: ["コンテナ", "秘密情報"],
    createdAt: "2026-09-01T00:00:00.000Z",
  },
  {
    id: "seed-machine-backup-review",
    createdBy: "seed-user-carol",
    name: "バックアップ調査",
    description: "バックアップファイルの保存場所と権限を調べ、不要な公開を防ぐ公開マシンです。",
    level: "easy",
    systemFlag: "flag{seed-backup-review}",
    userFlag: "",
    tags: ["データベース", "権限管理"],
    createdAt: "2026-09-02T00:00:00.000Z",
  },
  {
    id: "seed-machine-tls-certificate",
    createdBy: "seed-user-alice",
    name: "TLS証明書確認",
    description: "TLS証明書とサーバー設定を確認し、安全な通信の基本を学ぶ公開マシンです。",
    level: "easy",
    systemFlag: "flag{seed-tls-certificate}",
    userFlag: "",
    tags: ["Web セキュリティ", "暗号化"],
    createdAt: "2026-09-03T00:00:00.000Z",
  },
] as const

export const SEED_SOLUTIONS = [
  {
    userId: "seed-user-alice",
    machineId: "seed-machine-container-network",
    flagKind: "system",
    solvedAt: "2026-08-10T00:00:00.000Z",
  },
  {
    userId: "seed-user-bob",
    machineId: "seed-machine-web-auth",
    flagKind: "user",
    solvedAt: "2026-08-11T00:00:00.000Z",
  },
  {
    userId: "seed-user-carol",
    machineId: "seed-machine-linux-permissions",
    flagKind: "system",
    solvedAt: "2026-08-15T00:00:00.000Z",
  },
  {
    userId: "seed-user-alice",
    machineId: "seed-machine-log-trail",
    flagKind: "user",
    solvedAt: "2026-08-19T00:00:00.000Z",
  },
  {
    userId: "seed-user-carol",
    machineId: "seed-machine-api-authorization",
    flagKind: "system",
    solvedAt: "2026-08-22T00:00:00.000Z",
  },
  {
    userId: "seed-user-bob",
    machineId: "seed-machine-sql-investigation",
    flagKind: "system",
    solvedAt: "2026-08-25T00:00:00.000Z",
  },
  {
    userId: "seed-user-carol",
    machineId: "seed-machine-http-headers",
    flagKind: "system",
    solvedAt: "2026-08-27T00:00:00.000Z",
  },
  {
    userId: "seed-user-alice",
    machineId: "seed-machine-ssh-access",
    flagKind: "system",
    solvedAt: "2026-08-28T00:00:00.000Z",
  },
  {
    userId: "seed-user-bob",
    machineId: "seed-machine-dns-records",
    flagKind: "system",
    solvedAt: "2026-08-29T00:00:00.000Z",
  },
  {
    userId: "seed-user-carol",
    machineId: "seed-machine-session-cookie",
    flagKind: "user",
    solvedAt: "2026-08-30T00:00:00.000Z",
  },
  {
    userId: "seed-user-alice",
    machineId: "seed-machine-firewall-rules",
    flagKind: "system",
    solvedAt: "2026-08-31T00:00:00.000Z",
  },
  {
    userId: "seed-user-bob",
    machineId: "seed-machine-audit-log",
    flagKind: "user",
    solvedAt: "2026-09-01T00:00:00.000Z",
  },
  {
    userId: "seed-user-carol",
    machineId: "seed-machine-api-rate-limit",
    flagKind: "system",
    solvedAt: "2026-09-02T00:00:00.000Z",
  },
  {
    userId: "seed-user-alice",
    machineId: "seed-machine-container-secrets",
    flagKind: "system",
    solvedAt: "2026-09-03T00:00:00.000Z",
  },
  {
    userId: "seed-user-bob",
    machineId: "seed-machine-backup-review",
    flagKind: "system",
    solvedAt: "2026-09-04T00:00:00.000Z",
  },
  {
    userId: "seed-user-carol",
    machineId: "seed-machine-tls-certificate",
    flagKind: "system",
    solvedAt: "2026-09-05T00:00:00.000Z",
  },
] as const
